=== mboyer23/SOA-et-Interop/enseignants.dtd
<!-- EXERCICE 2 -->
<!ELEMENT enseignants ( enseignant* ) >
<!ELEMENT enseignant ( nom, prenoms, age?, annee?) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenoms (prenom+) >
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA) >
<!ELEMENT annee (#PCDATA) >
<!ATTLIST enseignants
annee CDATA #IMPLIED>
<!ATTLIST enseignant
dep CDATA #REQUIRED>
<!ENTITY dep "ISIS" >

=== mboyer23/SOA-et-Interop/tp1.xml
<!DOCTYPE enseignants SYSTEM "enseignants.dtd" >

<!-- EXERCICE 1 -->

<enseignants annee="2022">
    <enseignant dep="&dep;">
        <nom> Singer </nom>
        <prenoms> 
            <prenom> Nicolas </prenom>
            <prenom> Prenom </prenom>
        </prenoms>
    </enseignant>
    
    <enseignant dep="&dep;">
        <nom> Trouilhet </nom>
        <prenoms> 
            <prenom> Sylvie </prenom>
        </prenoms>
        <age> 38 </age>
    </enseignant>
</enseignants>

<!-- FORMAT JSON
{
	"enseignants": {
		"enseignant": [
			{
				"nom": "Singer",
				"prenom": "Nicolas",
				"_dep": "ISIS"
			},
			{
				"nom": "Trouilhet",
				"prenom": "Sylvie",
				"age": "38",
				"_dep": "ISIS"
			}
		]
	}
}
-->
